### ISSUE TITLE
Add animations for Cindy ducking

### ISSUE THREAD

**Issue by JSchoppe** [JSchoppe/CindyBrock-LegendOfTheKeytar#30]
Request to add animations (transitioned to from standing) of Cindy ducking down to avoid bullets. An idle state for ducking is required and the transition to ducking is optional in the case that Unity transitions it well enough.

**Comment by JSchoppe** [comment]
@IanJeannin when the player is ducking should they be able to move? If so does that prevent the use of abilities?

**Comment by IanJeannin** [comment]
They should not no. 
As for using abilities, we would need to add another round of animations for that, so I would say just disable until the player is no longer crouching.
