### ISSUE TITLE
Display resolution and scaling affects surface editor raycast. 

### ISSUE THREAD

**Issue by IanJeannin** [JSchoppe/CindyBrock-LegendOfTheKeytar#5]
Step 1) Change resolution scaling in Windows Display Settings to 125%.
Step 2) Attempt to edit the surface layout. Where you click in the editor is now slightly off, with accuracy decreased if zoomed further out. 

Steps to fix currently:
- Make sure Scale and Layout is changed to 100%. (Note: This affects all apps on the computer, resulting in smaller text and other issues.)

**Comment by JSchoppe** [comment]
@IanJeannin I have pushed and created a pull request [Fixes Pixel Scaling Offset #6](https://github.com/JSchoppe/BattleRoyalRhythm/pull/6) on the `movement-grid` branch. Can you switch over to this branch and confirm that this fix works on your machine?

**Comment by IanJeannin** [comment]
Confirmed this works. Tested on 100% Scaling, 125% scaling (default on my pc), and 300% scaling.
